apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgresql
    access: proxy
    url: postgres:5432
    user: openqilin
    isDefault: false
    editable: false
    secureJsonData:
      password: openqilin
    jsonData:
      database: openqilin
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
